/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ValidateIdsRouteImport } from './routes/validate/ids'
import { Route as StringsJsonFormatRouteImport } from './routes/strings/json-format'
import { Route as StringsCompareRouteImport } from './routes/strings/compare'
import { Route as GenerateJsonRouteImport } from './routes/generate/json'
import { Route as GenerateIdsRouteImport } from './routes/generate/ids'
import { Route as GenerateFakerRouteImport } from './routes/generate/faker'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidateIdsRoute = ValidateIdsRouteImport.update({
  id: '/validate/ids',
  path: '/validate/ids',
  getParentRoute: () => rootRouteImport,
} as any)
const StringsJsonFormatRoute = StringsJsonFormatRouteImport.update({
  id: '/strings/json-format',
  path: '/strings/json-format',
  getParentRoute: () => rootRouteImport,
} as any)
const StringsCompareRoute = StringsCompareRouteImport.update({
  id: '/strings/compare',
  path: '/strings/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateJsonRoute = GenerateJsonRouteImport.update({
  id: '/generate/json',
  path: '/generate/json',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateIdsRoute = GenerateIdsRouteImport.update({
  id: '/generate/ids',
  path: '/generate/ids',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateFakerRoute = GenerateFakerRouteImport.update({
  id: '/generate/faker',
  path: '/generate/faker',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/generate/faker': typeof GenerateFakerRoute
  '/generate/ids': typeof GenerateIdsRoute
  '/generate/json': typeof GenerateJsonRoute
  '/strings/compare': typeof StringsCompareRoute
  '/strings/json-format': typeof StringsJsonFormatRoute
  '/validate/ids': typeof ValidateIdsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/generate/faker': typeof GenerateFakerRoute
  '/generate/ids': typeof GenerateIdsRoute
  '/generate/json': typeof GenerateJsonRoute
  '/strings/compare': typeof StringsCompareRoute
  '/strings/json-format': typeof StringsJsonFormatRoute
  '/validate/ids': typeof ValidateIdsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/generate/faker': typeof GenerateFakerRoute
  '/generate/ids': typeof GenerateIdsRoute
  '/generate/json': typeof GenerateJsonRoute
  '/strings/compare': typeof StringsCompareRoute
  '/strings/json-format': typeof StringsJsonFormatRoute
  '/validate/ids': typeof ValidateIdsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/generate/faker'
    | '/generate/ids'
    | '/generate/json'
    | '/strings/compare'
    | '/strings/json-format'
    | '/validate/ids'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/generate/faker'
    | '/generate/ids'
    | '/generate/json'
    | '/strings/compare'
    | '/strings/json-format'
    | '/validate/ids'
  id:
    | '__root__'
    | '/'
    | '/generate/faker'
    | '/generate/ids'
    | '/generate/json'
    | '/strings/compare'
    | '/strings/json-format'
    | '/validate/ids'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GenerateFakerRoute: typeof GenerateFakerRoute
  GenerateIdsRoute: typeof GenerateIdsRoute
  GenerateJsonRoute: typeof GenerateJsonRoute
  StringsCompareRoute: typeof StringsCompareRoute
  StringsJsonFormatRoute: typeof StringsJsonFormatRoute
  ValidateIdsRoute: typeof ValidateIdsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validate/ids': {
      id: '/validate/ids'
      path: '/validate/ids'
      fullPath: '/validate/ids'
      preLoaderRoute: typeof ValidateIdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strings/json-format': {
      id: '/strings/json-format'
      path: '/strings/json-format'
      fullPath: '/strings/json-format'
      preLoaderRoute: typeof StringsJsonFormatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strings/compare': {
      id: '/strings/compare'
      path: '/strings/compare'
      fullPath: '/strings/compare'
      preLoaderRoute: typeof StringsCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate/json': {
      id: '/generate/json'
      path: '/generate/json'
      fullPath: '/generate/json'
      preLoaderRoute: typeof GenerateJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate/ids': {
      id: '/generate/ids'
      path: '/generate/ids'
      fullPath: '/generate/ids'
      preLoaderRoute: typeof GenerateIdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate/faker': {
      id: '/generate/faker'
      path: '/generate/faker'
      fullPath: '/generate/faker'
      preLoaderRoute: typeof GenerateFakerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GenerateFakerRoute: GenerateFakerRoute,
  GenerateIdsRoute: GenerateIdsRoute,
  GenerateJsonRoute: GenerateJsonRoute,
  StringsCompareRoute: StringsCompareRoute,
  StringsJsonFormatRoute: StringsJsonFormatRoute,
  ValidateIdsRoute: ValidateIdsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
