/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StringsJsonFormatRouteImport } from './routes/strings/json-format'
import { Route as GenerateIdsRouteImport } from './routes/generate/ids'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StringsJsonFormatRoute = StringsJsonFormatRouteImport.update({
  id: '/strings/json-format',
  path: '/strings/json-format',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateIdsRoute = GenerateIdsRouteImport.update({
  id: '/generate/ids',
  path: '/generate/ids',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/generate/ids': typeof GenerateIdsRoute
  '/strings/json-format': typeof StringsJsonFormatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/generate/ids': typeof GenerateIdsRoute
  '/strings/json-format': typeof StringsJsonFormatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/generate/ids': typeof GenerateIdsRoute
  '/strings/json-format': typeof StringsJsonFormatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/generate/ids' | '/strings/json-format'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/generate/ids' | '/strings/json-format'
  id: '__root__' | '/' | '/generate/ids' | '/strings/json-format'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GenerateIdsRoute: typeof GenerateIdsRoute
  StringsJsonFormatRoute: typeof StringsJsonFormatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strings/json-format': {
      id: '/strings/json-format'
      path: '/strings/json-format'
      fullPath: '/strings/json-format'
      preLoaderRoute: typeof StringsJsonFormatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate/ids': {
      id: '/generate/ids'
      path: '/generate/ids'
      fullPath: '/generate/ids'
      preLoaderRoute: typeof GenerateIdsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GenerateIdsRoute: GenerateIdsRoute,
  StringsJsonFormatRoute: StringsJsonFormatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
